service_name = "data-backup"
port = 8080
# 每天凌晨 3 点
default_cron = "0 3 * * * *"

[logger]
    level = "info"
    filename = "log/data-backup.log"

[email]
    host="smtp.qq.com"
    port=587
    username="ihezebin@qq.com"
    password="xxxxx"

[[mongo_sources]]
    id = "mongo:blog"
    dsn = "mongodb://root:root@127.0.0.1:27017/blog?authSource=admin"
    collections = ["article", "tag", "draft", "comment"]
#[[mysql_sources]]
#    id = "blog"
#    dsn = "root:root@tcp(mysql-service:3306)/blog?charset=utf8mb4&parseTime=True&loc=Local"
#    collections = ["article", "tag", "draft", "comment"]
[[minio_sources]]
    id = "minio:blog"
    dsn = "minio://xxx:xxx@127.0.0.1:9000/blog-minio"
    prefix = ["preview", "content"]

[[oss_targets]]
    id = "cos:hezebin:backup:mongo"
    dsn = "cos://xxx:xxx@cos.ap-chengdu.myqcloud.com/hezebin-1258606727"
    dir = "backup_mongo"
[[oss_targets]]
    id = "cos:hezebin:backup:minio"
    dsn = "cos://xxx:xxx@cos.ap-chengdu.myqcloud.com/hezebin-1258606727"
    dir = "backup_minio"


[[tasks]]
    id = "664c72b790d71012f2753739"
    cron = "0 1 * * * *"
    source_id = "mongo:blog"
    target_id = "cos:hezebin:backup"


#[redis_nodes]
#    addrs = ["127.0.0.1:6379"]
#    password = "root"
#addrs = ["redis-sts-0.redis.default:7000", "redis-sts-1.redis.default:7000", "redis-sts-2.redis.default:7000"]
#password = "root"