// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/restore/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restore"
                ],
                "summary": "通过备份任务来恢复数据",
                "parameters": [
                    {
                        "description": "任务参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RestoreByTaskReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功时如下结构；错误时 code 非 0, message 包含错误信息, 不包含 data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/server.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RestoreByTaskResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.RestoreByTaskReq": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                }
            }
        },
        "dto.RestoreByTaskResp": {
            "type": "object",
            "properties": {
                "task": {
                    "$ref": "#/definitions/task.Task"
                }
            }
        },
        "server.Body": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "task.Task": {
            "type": "object",
            "properties": {
                "cron": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "source": {},
                "source_id": {
                    "type": "string"
                },
                "target": {},
                "target_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go Template DDD 示例 API 文档",
	Description:      "这是一个使用 Gin 和 Swagger 生成 API 文档的示例。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
